### ISSUE TITLE
Error installing Epinio/Tekton on k3d

### ISSUE THREAD

**Issue by jbbarth** [epinio/epinio#404]
I'm trying to install epinio with k3d and get the following error:
```
panic: Deployment tekton failed with error: Installing staging pipelines and triggers failed:
Error from server (InternalError): error when creating "/var/folders/_w/3smgfp3j0jl2y0xlg8cyp7tm0000gq/T/epinio095441293": Internal error occurred: failed calling webhook "webhook.triggers.tekton.dev": Post "https://tekton-triggers-webhook.tekton.svc:443/defaulting?timeout=10s": dial tcp 10.43.179.28:443: connect: connection refused
Error from server (InternalError): error when creating "/var/folders/_w/3smgfp3j0jl2y0xlg8cyp7tm0000gq/T/epinio095441293": Internal error occurred: failed calling webhook "webhook.triggers.tekton.dev": Post "https://tekton-triggers-webhook.tekton.svc:443/defaulting?timeout=10s": dial tcp 10.43.179.28:443: connect: connection refused
Error from server (InternalError): error when creating "/var/folders/_w/3smgfp3j0jl2y0xlg8cyp7tm0000gq/T/epinio095441293": Internal error occurred: failed calling webhook "webhook.triggers.tekton.dev": Post "https://tekton-triggers-webhook.tekton.svc:443/defaulting?timeout=10s": dial tcp 10.43.179.28:443: connect: connection refused
Error from server (InternalError): error when creating "/var/folders/_w/3smgfp3j0jl2y0xlg8cyp7tm0000gq/T/epinio095441293": Internal error occurred: failed calling webhook "webhook.pipeline.tekton.dev": Post "https://tekton-pipelines-webhook.tekton.svc:443/defaulting?timeout=10s": dial tcp 10.43.193.208:443: connect: connection refused
Error from server (InternalError): error when creating "/var/folders/_w/3smgfp3j0jl2y0xlg8cyp7tm0000gq/T/epinio095441293": Internal error occurred: failed calling webhook "webhook.pipeline.tekton.dev": Post "https://tekton-pipelines-webhook.tekton.svc:443/defaulting?timeout=10s": dial tcp 10.43.193.208:443: connect: connection refused
Error from server (InternalError): error when creating "/var/folders/_w/3smgfp3j0jl2y0xlg8cyp7tm0000gq/T/epinio095441293": Internal error occurred: failed calling webhook "webhook.pipeline.tekton.dev": Post "https://tekton-pipelines-webhook.tekton.svc:443/defaulting?timeout=10s": dial tcp 10.43.193.208:443: connect: connection refused
```

I can see the services present with kubectl:
```
% k get svc --namespace=tekton
NAME                                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                              AGE
tekton-pipelines-controller         ClusterIP   10.43.138.5     <none>        9090/TCP,8080/TCP                    10m
tekton-pipelines-webhook            ClusterIP   10.43.193.208   <none>        9090/TCP,8008/TCP,443/TCP,8080/TCP   10m
tekton-triggers-controller          ClusterIP   10.43.5.176     <none>        9090/TCP                             10m
tekton-triggers-core-interceptors   ClusterIP   10.43.98.168    <none>        80/TCP                               10m
tekton-triggers-webhook             ClusterIP   10.43.179.28    <none>        443/TCP                              10m
```

And the service responds from a pod in the same namespace (with "curl"), tho I can't guarantee they were there and working at the time the POST request that fails was made. I tried this multiple times and get the same failing request on the same services each time.

I'd take any help to debug that ! Thanks !

<details>
<summary>Here are my versions if it helps :</summary>

```
% sw_vers
ProductName:	macOS
ProductVersion:	11.3
BuildVersion:	20E232

% k3d --version
k3d version v4.4.3
k3s version latest (default)

% epinio --version
epinio version v0.0.12

% docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.12
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

</details>

**Comment by andreas-kupries** [comment]
When you say `I'm trying to install Tekton with k3d and get the following error:` ... Is this a shorthand for `I am invoking "epinio install" and it fails when it comes to deploying the tekton component` ?

Or are you indeed manually installing tekton before trying to install epinio itself, as the phrasing implies ?

As a datapoint from me, I have no trouble installing epinio from the head of the main branch, on a slightly older k3d, on linux (Leap 15.2).
Ok, so different from yours in 3 axes: k3d version, ep version, and underlying OS.

```
work@tagetarl:~/SUSE/dev/epinio> ep --version
epinio version v0.0.12-51-g3381b76
work@tagetarl:~/SUSE/dev/epinio> k3d --version
k3d version v4.2.0
k3s version v1.20.2-k3s1 (default)
```

If you are willing to try the head instead of the last release note that installation needs a slightly different set of commands:

```
epinio install --skip-default-org
make patch-epinio-deployment
sleep 30
epinio org create workspace
epinio target workspace
```

This is due to us having to patch the local epinio binary into the epinio server pod, replacing the missing binary in the image, for a commit which is not released.

Note that past 0.0.12 we reworked the entire push process. From the tekton point of view we took out the event listener and the gitea webhook. The epinio server now explicitly creates the necessary PipelineRun objects, instead of a brittle chain of hooks.

This alone may fix your issue, assuming that the webhook referenced by the error messages is the same we got rid of.

**Comment by jbbarth** [comment]
> When you say I'm trying to install Tekton with k3d and get the following error: ... Is this a shorthand for I am invoking "epinio install" and it fails when it comes to deploying the tekton component ?

Yay, sorry, I should have proof  read myself, I meant "trying to install epinio" of course. I have no specificity about Tekton (and 0 knowledge about it btw). I'm doing the following :
```
k3d cluster create epinio
epinio install
```
<details>
<summary>Full log</summary>

```
% k3d cluster create epinio
INFO[0000] Prep: Network
INFO[0003] Created network 'k3d-epinio' (5beddc448faf3529d2cea94c1d9cffe0feaf59f619ea3c320e4a025a6e326fbb)
INFO[0003] Created volume 'k3d-epinio-images'
INFO[0004] Creating node 'k3d-epinio-server-0'
INFO[0004] Creating LoadBalancer 'k3d-epinio-serverlb'
INFO[0005] Starting cluster 'epinio'
INFO[0005] Starting servers...
INFO[0005] Starting Node 'k3d-epinio-server-0'
INFO[0013] Starting agents...
INFO[0013] Starting helpers...
INFO[0013] Starting Node 'k3d-epinio-serverlb'
INFO[0016] (Optional) Trying to get IP of the docker host and inject it into the cluster as 'host.k3d.internal' for easy access
INFO[0018] Successfully added host record to /etc/hosts in 2/2 nodes and to the CoreDNS ConfigMap
INFO[0018] Cluster 'epinio' created successfully!
INFO[0018] --kubeconfig-update-default=false --> sets --kubeconfig-switch-context=false
INFO[0018] You can now use it like this:
kubectl config use-context k3d-epinio
kubectl cluster-info
% epinio install

🚢 Epinio installing...

Configuration...
  🧭  system_domain:
  🧭  email_address: epinio@suse.com

🚢 Deploying Traefik Ingress........................
✔️  Traefik Ingress deployed
.
✔️  Created system_domain: 172.22.0.2.omg.howdoi.website

🚢 Deploying Gitea...
🚢 Deploying ServiceCatalog...
🚢 Deploying Registry...
🚢 Deploying Epinio...
🚢 Deploying Quarks...
🚢 Deploying CertManager...
🚢 Deploying Tekton....I0518 09:11:12.845132    3870 request.go:655] Throttling request took 1.154559642s, request: POST:https://0.0.0.0:50340/api/v1/namespaces
...............................................................................I0518 09:11:29.393328    3870 request.go:655] Throttling request took 1.071858272s, request: GET:https://0.0.0.0:50340/api/v1/namespaces/service-catalog/pods/service-catalog-catalog-controller-manager-779dd58cd8-qgjxn
.........................................................................I0518 09:11:39.791901    3870 request.go:655] Throttling request took 1.152182372s, request: GET:https://0.0.0.0:50340/api/v1/namespaces/quarks/pods/quarks-secret-599fd66d8d-xhh8m
........................................................................I0518 09:11:50.189602    3870 request.go:655] Throttling request took 1.001038777s, request: GET:https://0.0.0.0:50340/api/v1/namespaces/gitea/pods/gitea-memcached-c8547c9c9-clnk2
...................................................................panic: Deployment tekton failed with error: Installing staging pipelines and triggers failed:
Error from server (InternalError): error when creating "/var/folders/_w/3smgfp3j0jl2y0xlg8cyp7tm0000gq/T/epinio095441293": Internal error occurred: failed calling webhook "webhook.triggers.tekton.dev": Post "https://tekton-triggers-webhook.tekton.svc:443/defaulting?timeout=10s": dial tcp 10.43.179.28:443: connect: connection refused
Error from server (InternalError): error when creating "/var/folders/_w/3smgfp3j0jl2y0xlg8cyp7tm0000gq/T/epinio095441293": Internal error occurred: failed calling webhook "webhook.triggers.tekton.dev": Post "https://tekton-triggers-webhook.tekton.svc:443/defaulting?timeout=10s": dial tcp 10.43.179.28:443: connect: connection refused
Error from server (InternalError): error when creating "/var/folders/_w/3smgfp3j0jl2y0xlg8cyp7tm0000gq/T/epinio095441293": Internal error occurred: failed calling webhook "webhook.triggers.tekton.dev": Post "https://tekton-triggers-webhook.tekton.svc:443/defaulting?timeout=10s": dial tcp 10.43.179.28:443: connect: connection refused
Error from server (InternalError): error when creating "/var/folders/_w/3smgfp3j0jl2y0xlg8cyp7tm0000gq/T/epinio095441293": Internal error occurred: failed calling webhook "webhook.pipeline.tekton.dev": Post "https://tekton-pipelines-webhook.tekton.svc:443/defaulting?timeout=10s": dial tcp 10.43.193.208:443: connect: connection refused
Error from server (InternalError): error when creating "/var/folders/_w/3smgfp3j0jl2y0xlg8cyp7tm0000gq/T/epinio095441293": Internal error occurred: failed calling webhook "webhook.pipeline.tekton.dev": Post "https://tekton-pipelines-webhook.tekton.svc:443/defaulting?timeout=10s": dial tcp 10.43.193.208:443: connect: connection refused
Error from server (InternalError): error when creating "/var/folders/_w/3smgfp3j0jl2y0xlg8cyp7tm0000gq/T/epinio095441293": Internal error occurred: failed calling webhook "webhook.pipeline.tekton.dev": Post "https://tekton-pipelines-webhook.tekton.svc:443/defaulting?timeout=10s": dial tcp 10.43.193.208:443: connect: connection refused
: exit status 1


goroutine 49 [running]:
github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Install.func1(0xc00061ae10, 0x2a83428, 0xc000625090, 0x2a88c88, 0xc0005780c0, 0xc000469024)
	/home/runner/work/epinio/epinio/internal/cli/clients/install_client.go:136 +0x217
created by github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Install
	/home/runner/work/epinio/epinio/internal/cli/clients/install_client.go:133 +0xba5
```

</details>

Thanks a lot for the quick answer and the details, I'll try the head commit and will tell you how it works.

**Comment by andreas-kupries** [comment]
The panic comes from https://github.com/epinio/epinio/blob/main/internal/cli/clients/install_client.go#L155
And we know that it is running the tekton deployment.
Unfortunately no details.
You can use `--verbosity 1` to get more user-level details out of the install.
Looking into the code (https://github.com/epinio/epinio/blob/main/deployments/tekton.go#L134-L264) using `--trace-level` will not help. There is no logging in that area :(

**Comment by andreas-kupries** [comment]
Got myself `k3d v4.4.3`, and installed epinio main head. Deploys fine. 

Table of data points so far:

|ep version|k3d version|OS|State|
|---|---|---|---|
|0.0.12|4.4.3|OS X| :boom: |
|0.0.12-57-gb117738|4.4.3|Leap 15.2| :heavy_check_mark: |
|0.0.12-57-gb117738|4.2.0|Leap 15.2| :heavy_check_mark: |

If your attempt using the head of main branch fails, then that would point to some OS problem ?! (OS X vs. Linux).

**Comment by jbbarth** [comment]
No much luck with the verbose logs unfortunately:

<details>
<summary>Logs</summary>

```
[...]
🕞   Establish CRD taskruns.tekton.dev .

🕞   Establish CRD tasks.tekton.dev ..

🕞   Establish CRD triggerbindings.triggers.tekton.dev ..

🕞   Establish CRD triggers.triggers.tekton.dev ..

🕞   Establish CRD triggertemplates.triggers.tekton.dev .

🕞   Installing staging pipelines and triggers ........
panic: Deployment tekton failed with error: Installing staging pipelines and triggers failed:
Error from server (InternalError): error when creating "/var/folders/_w/3smgfp3j0jl2y0xlg8cyp7tm0000gq/T/epinio628997877": Internal error occurred: failed calling webhook "webhook.triggers.tekton.dev": Post "https://tekton-triggers-webhook.tekton.svc:443/defaulting?timeout=10s": dial tcp 10.43.169.149:443: connect: connection refused
Error from server (InternalError): error when creating "/var/folders/_w/3smgfp3j0jl2y0xlg8cyp7tm0000gq/T/epinio628997877": Internal error occurred: failed calling webhook "webhook.triggers.tekton.dev": Post "https://tekton-triggers-webhook.tekton.svc:443/defaulting?timeout=10s": dial tcp 10.43.169.149:443: connect: connection refused
Error from server (InternalError): error when creating "/var/folders/_w/3smgfp3j0jl2y0xlg8cyp7tm0000gq/T/epinio628997877": Internal error occurred: failed calling webhook "webhook.triggers.tekton.dev": Post "https://tekton-triggers-webhook.tekton.svc:443/defaulting?timeout=10s": dial tcp 10.43.169.149:443: connect: connection refused
Error from server (InternalError): error when creating "/var/folders/_w/3smgfp3j0jl2y0xlg8cyp7tm0000gq/T/epinio628997877": Internal error occurred: failed calling webhook "webhook.pipeline.tekton.dev": Post "https://tekton-pipelines-webhook.tekton.svc:443/defaulting?timeout=10s": dial tcp 10.43.205.218:443: connect: connection refused
Error from server (InternalError): error when creating "/var/folders/_w/3smgfp3j0jl2y0xlg8cyp7tm0000gq/T/epinio628997877": Internal error occurred: failed calling webhook "webhook.pipeline.tekton.dev": Post "https://tekton-pipelines-webhook.tekton.svc:443/defaulting?timeout=10s": dial tcp 10.43.205.218:443: connect: connection refused
Error from server (InternalError): error when creating "/var/folders/_w/3smgfp3j0jl2y0xlg8cyp7tm0000gq/T/epinio628997877": Internal error occurred: failed calling webhook "webhook.pipeline.tekton.dev": Post "https://tekton-pipelines-webhook.tekton.svc:443/defaulting?timeout=10s": dial tcp 10.43.205.218:443: connect: connection refused
: exit status 1


goroutine 84 [running]:
github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Install.func1(0xc0003befc0, 0x2a83428, 0xc0003ce5a0, 0x2a88c88, 0xc000847940, 0xc0006b0e54)
	/home/runner/work/epinio/epinio/internal/cli/clients/install_client.go:136 +0x217
created by github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Install
	/home/runner/work/epinio/epinio/internal/cli/clients/install_client.go:133 +0xba5
```

</details>

With a head binary I don't get an error on the `webhook.triggers.tekton.dev` webhook anymore (progress!) but I still get an error on the other one (`webhook.pipeline.tekton.dev`).

<details>
<summary>Full logs with epinio@HEAD</summary>

```
% k3d cluster create epinio
INFO[0000] Prep: Network
INFO[0003] Created network 'k3d-epinio' (d2277d6ec32d33fb529f50553ae302742d3507cf4b57ef51b173381d202c71a8)
INFO[0003] Created volume 'k3d-epinio-images'
INFO[0004] Creating node 'k3d-epinio-server-0'
INFO[0004] Creating LoadBalancer 'k3d-epinio-serverlb'
INFO[0004] Starting cluster 'epinio'
INFO[0004] Starting servers...
INFO[0004] Starting Node 'k3d-epinio-server-0'
INFO[0013] Starting agents...
INFO[0013] Starting helpers...
INFO[0013] Starting Node 'k3d-epinio-serverlb'
INFO[0016] (Optional) Trying to get IP of the docker host and inject it into the cluster as 'host.k3d.internal' for easy access
INFO[0021] Successfully added host record to /etc/hosts in 2/2 nodes and to the CoreDNS ConfigMap
INFO[0021] Cluster 'epinio' created successfully!
INFO[0021] --kubeconfig-update-default=false --> sets --kubeconfig-switch-context=false
INFO[0021] You can now use it like this:
kubectl config use-context k3d-epinio
kubectl cluster-info
% make build-darwin
go fmt ./...
assets/statikWebViews/statik.go
assets/statik/statik.go
assets/statikWebAssets/statik.go
go mod tidy
( [ -x "$(command -v statik)" ] || go get github.com/rakyll/statik@v0.1.7 )
statik -m -f -src=./assets/embedded-files -dest assets
statik -m -f -src=./assets/embedded-web-files/views -ns webViews -p statikWebViews -dest assets
statik -m -f -src=./assets/embedded-web-files/assets -ns webAssets -p statikWebAssets -dest assets
go vet ./...
GOARCH="amd64" GOOS="darwin" CGO_ENABLED=0 go build  -ldflags '-X github.com/epinio/epinio/internal/version.Version=v0.0.12-57-gb117738' -o dist/epinio-darwin-amd64
% alias epinio=/Users/jean-baptistebarth/dev/epinio/epinio/dist/epinio-darwin-amd64
% epinio --version
epinio version v0.0.12-57-gb117738
% git log --format=oneline @~1..@
b117738fd3f461ac5b632dfb395a7626309b9830 (HEAD -> main, origin/main, origin/HEAD) Merge pull request #400 from epinio/246-wait-for-tekton
274b8a2ff09b0b327244818dfd4562bf184355ef Fix typos in comments
1cb778d1ead41d490c49dac74681c841f4252547 Wait for tekton pipelerun to complete
ef0a218df3534294c095958d74847ce847798e4e Wait for specific app to run
% epinio install --skip-default-org


🚢 Epinio installing...

Configuration...
  🧭  system_domain:
  🧭  email_address: epinio@suse.com
  🧭  user: me
  🧭  password: change

⚠️  Traefik Ingress already installed, skipping
.
✔️  Created system_domain: 172.24.0.2.omg.howdoi.website

🚢 Deploying CertManager...
🚢 Deploying Registry...
🚢 Deploying Tekton...
🚢 Deploying Gitea...
🚢 Deploying Epinio...
🚢 Deploying ServiceCatalog...
🚢 Deploying Quarks....I0518 15:53:12.012279   15462 request.go:655] Throttling request took 1.123008831s, request: POST:https://0.0.0.0:53304/api/v1/namespaces
...............................................................I0518 15:53:30.034641   15462 request.go:655] Throttling request took 1.091250086s, request: GET:https://0.0.0.0:53304/api/v1/namespaces/gitea/pods/gitea-memcached-c8547c9c9-lvh7p
........................................................................I0518 15:53:40.232563   15462 request.go:655] Throttling request took 1.288352618s, request: GET:https://0.0.0.0:53304/api/v1/namespaces/gitea/pods/gitea-memcached-c8547c9c9-lvh7p
.............................................................................I0518 15:53:51.232023   15462 request.go:655] Throttling request took 1.011859107s, request: GET:https://0.0.0.0:53304/api/v1/namespaces/epinio/pods/epinio-server-697d8cf49-bcb9k
......................................................................I0518 15:54:01.234337   15462 request.go:655] Throttling request took 1.293698544s, request: GET:https://0.0.0.0:53304/api/v1/namespaces/gitea/pods/gitea-memcached-c8547c9c9-lvh7p
.............................................................................I0518 15:54:12.231675   15462 request.go:655] Throttling request took 1.009120328s, request: GET:https://0.0.0.0:53304/api/v1/namespaces/epinio/pods/epinio-server-697d8cf49-bcb9k
..................................................................
✔️  ServiceCatalog deployed
.....I0518 15:54:22.234821   15462 request.go:655] Throttling request took 1.337619549s, request: GET:https://0.0.0.0:53304/api/v1/namespaces/tekton/pods/tekton-pipelines-webhook-75d465b94f-lglgp
.................................................
✔️  Quarks deployed
..............................................................................
✔️  CertManager deployed
...................................................................................panic: Deployment tekton failed with error: Installing staging pipelines failed:
Error from server (InternalError): error when creating "/var/folders/_w/3smgfp3j0jl2y0xlg8cyp7tm0000gq/T/epinio934880935": Internal error occurred: failed calling webhook "webhook.pipeline.tekton.dev": Post "https://tekton-pipelines-webhook.tekton.svc:443/defaulting?timeout=10s": dial tcp 10.43.28.77:443: connect: connection refused
Error from server (InternalError): error when creating "/var/folders/_w/3smgfp3j0jl2y0xlg8cyp7tm0000gq/T/epinio934880935": Internal error occurred: failed calling webhook "webhook.pipeline.tekton.dev": Post "https://tekton-pipelines-webhook.tekton.svc:443/defaulting?timeout=10s": dial tcp 10.43.28.77:443: connect: connection refused
Error from server (InternalError): error when creating "/var/folders/_w/3smgfp3j0jl2y0xlg8cyp7tm0000gq/T/epinio934880935": Internal error occurred: failed calling webhook "webhook.pipeline.tekton.dev": Post "https://tekton-pipelines-webhook.tekton.svc:443/defaulting?timeout=10s": dial tcp 10.43.28.77:443: connect: connection refused
: exit status 1


goroutine 66 [running]:
github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Install.func1(0xc0005775c0, 0x2cc9460, 0xc0000d0d20, 0x2cd4b00, 0xc000606380, 0xc0005ed4a4)
	/Users/jean-baptistebarth/dev/epinio/epinio/internal/cli/clients/install_client.go:155 +0x245
created by github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Install
	/Users/jean-baptistebarth/dev/epinio/epinio/internal/cli/clients/install_client.go:152 +0xd26
% make patch-epinio-deployment

Creating the PVC
persistentvolumeclaim/epinio-binary created
Creating the dummy copier Pod
pod/epinio-copier created
Waiting for dummy pod to be ready
pod/epinio-copier condition met
Copying the binary on the PVC
error: dist/epinio-linux-amd64 doesn't exist in local filesystem
Patching the epinio-server deployment to use the copied binary
deployment.apps/epinio-server patched
Ensuring the deployment is restarted
deployment.apps/epinio-server restarted
Waiting for the rollout of the deployment to complete
Waiting for deployment "epinio-server" rollout to finish: 0 out of 1 new replicas have been updated...
Waiting for deployment "epinio-server" rollout to finish: 1 old replicas are pending termination...
error: timed out waiting for the condition
make: *** [patch-epinio-deployment] Error 1
% # I imagine it's normal here since the installation step above didn't finish correctly
```
</details>

**Comment by andreas-kupries** [comment]
> No much luck with the verbose logs unfortunately:

Actually it gives a more precise location in the code where things go off the rails.
 - https://github.com/epinio/epinio/blob/v0.0.12/deployments/tekton.go#L214
 - https://github.com/epinio/epinio/blob/v0.0.12/assets/embedded-files/tekton/triggers.yaml

And for the head binary
  - https://github.com/epinio/epinio/blob/main/deployments/tekton.go#L186
  - https://github.com/epinio/epinio/blob/main/assets/embedded-files/tekton/pipeline.yaml

The pipeline.yaml is a renamed triggers.yaml where the trigger resources got removed.

There are no explicit webhook references in these files.

Do you have access to a Leap 15.2 box ? If yes, can you check that it fails there also ?
At the moment, looking back at the [table](https://github.com/epinio/epinio/issues/404#issuecomment-843073577) and slotting in this new data the only difference between :boom: and :heavy_check_mark: looks to be the OS, i.e. darwin vs linux. And the differences in their docker implementations.

**Comment by jbbarth** [comment]
No access to a Leap box, but I may try to setup something next week. I will definitely try to debug locally too, there must be something wrong on my machine I guess you're right.

I ended up deploying epinio on a non-local Kubernetes cluster (at Scaleway fwiw) and it worked just fine, I can play with it for a moderate cost now ;-)

Thanks for your patience and your help !

**Comment by jimmykarily** [comment]
@jbbarth thank you for reporting the issue. @andreas-kupries thanks for the debugging so far. Let's keep this issue open to investigate a bit further. It would be good to know what went wrong. Maybe there is a race condition lurking.

We are waiting for the webhook to be running (here: https://github.com/epinio/epinio/blob/main/deployments/tekton.go#L156-L162) before we try to install the staging pipelines some lines further down the same file. Is it possible that the webhook pod appear and disappears right after? Maybe it's a resource issue (e.g. disk space) and kubernetes start killing pods?

**Comment by manno** [comment]
I'm testing with the latest HEAD (d6dc465).
I can reproduce the problem. As a workaround I was able to complete the tekton deployment, by adding `time.Sleep(15 * time.Second)` right before applying the `pipeline.yml`.
I'll try to figure out why the webhook is not ready, even though we checked the pod. Adding checks for the deployment and content of the `webhook-cert` didn't help.

**Comment by jbbarth** [comment]
The tekton webhook pod has a `readinessProbe` with a `initialDelaySeconds: 5`. So I guess checking for the pod existence won't guarantee the pod serves requests, and it can only do so after 5 seconds of existence in the best scenario ?

**Comment by jbbarth** [comment]
That makes sense, thanks for the analysis !
