### ISSUE TITLE
Epinio (cert-manager) uninstall fails with external-dns

### ISSUE THREAD

**Issue by svollath** [epinio/epinio#499]
### Description
When I run epinio uninstall, it will abort with `panic: failed to delete namespace: timed out waiting for the condition`

### Environment
Installed epinio-0.0.16 to RKE2 (v1.20.7+rke2r2) with metallb and external-dns.
So traefik will fetch a public IP from the metallb pool, and the traefik service got an annotation for its system-domain.
```
> epinio-0.0.16 install --system-domain tf1.paas.suse.de
> kubectl annotate --overwrite svc traefik -n traefik "external-dns.alpha.kubernetes.io/hostname=tf1.paas.suse.de, *.tf1.paas.suse.de"
```

### How to Reproduce
```
> ./epinio-0.0.16 --skip-ssl-verification uninstall
```

### Output
```
🚢 Epinio uninstalling...


🚢 Removing Quarks...🚢 Removing Epinio...

🚢 Removing Gitea...
🚢 Removing Traefik...
🚢 Removing Tekton...
🚢 Removing GoogleServices...
🚢 Removing CertManager...
🚢 Removing Registry...
🚢 Removing Minibroker...🚢 Removing ServiceCatalog...
⚠️  Skipping GoogleServices because namespace either doesn't exist or not owned by Epinio

⚠️  Skipping Minibroker because namespace either doesn't exist or not owned by Epinio
I0615 17:41:19.178069   28568 request.go:655] Throttling request took 1.15179504s, request: GET:https://tf1-cluster.paas.suse.de:6443/api/v1/namespaces/tekton-staging
.............................................................................
✔️  Gitea removed
.....
✔️  Quarks removed
.
✔️  Traefik removed
...
✔️  Registry removed
............................................................................................
✔️  ServiceCatalog removed
....................................
✔️  Tekton removed
............................................................................................................................................................................................................................................................panic: failed to delete namespace: timed out waiting for the condition

goroutine 61 [running]:
github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Uninstall.func1(0xc0002f0bd0, 0x20507b0, 0xc00008aaa0, 0x20562a0, 0xc0004a1660, 0xc0004a15d4)
        /home/runner/work/epinio/epinio/internal/cli/clients/install_client.go:242 +0xcb
created by github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Uninstall
        /home/runner/work/epinio/epinio/internal/cli/clients/install_client.go:239 +0x7ee
```

### Errors
```
message: 'Some content in the namespace has finalizers remaining: finalizer.acme.cert-manager.io
      in 1 resource instances'
```
```
│   Reason:      Error accepting authorization: acme: authorization error for epinio.tf1.paas.suse.de: 400 urn:ietf:params:acme:error:dns: DNS problem: NXDOMAIN looking up A for epinio.tf1.paas.suse.de - check that a DNS record exists f │
│ or this domain
```

### Summary
`epinio uninstall` removed traefik - and therefore the public IP/DNS - before cert-manager, which seems to need it on deletion.
This implies - if it's not a bug for cert-manager cleanup - that we might want to delete cert-manager before we do delete traefik.

### Notes
Also, regarding external-dns annotations and DNS providers involved, it seems we want to
- on `epinio install`: wait until `system-domain` resolves to the matching public traefik service IP, before we install cert-manager
- on `epinio install`: delete cert-manager, before we remove traefik

**Comment by svollath** [comment]
It's maybe not only about DNS, but about the externalIP as well, since I also run into trouble with a fixed DNS record for my DOMAIN, when poinint to the externalIP - it's also gone, when traefik get's deleted.

```
> ./epinio-0.0.17 uninstall --skip-ssl-verification

🚢 Epinio uninstalling...


🚢 Removing GoogleServices...
🚢 Removing Quarks...
🚢 Removing Minibroker...
🚢 Removing Gitea...🚢 Removing Epinio...
🚢 Removing ServiceCatalog...
🚢 Removing CertManager...
🚢 Removing Traefik...
🚢 Removing Tekton...
🚢 Removing Registry...
⚠️  Skipping Minibroker because namespace either doesn't exist or not owned by Epinio

⚠️  Skipping GoogleServices because namespace either doesn't exist or not owned by Epinio
I0621 15:33:34.872952    9353 request.go:655] Throttling request took 1.162355242s, request: GET:https://tf1-cluster.paas.suse.de:6443/api/v1/namespaces/gitea
.........................................................................
✔️  Gitea removed
........
✔️  Quarks removed
....
✔️  Traefik removed
...................................
✔️  Epinio removed
.panic: Failed uninstalling helm release epinio-registry: Error: uninstallation completed with 1 error(s): unable to build kubernetes objects for delete: unable to recognize "": no matches for kind "QuarksSecret" in version "quarks.cloudfoundry.org/v1alpha1"
: exit status 1

goroutine 24 [running]:
github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Uninstall.func1(0xc000450ff0, 0x20473f0, 0xc000040140, 0x2051b70, 0xc0002b64b0, 0x2057870, 0xc00030ff90, 0xc00030ff54)
        /home/runner/work/epinio/epinio/internal/cli/clients/install_client.go:252 +0xeb
created by github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Uninstall
        /home/runner/work/epinio/epinio/internal/cli/clients/install_client.go:249 +0x854
```

Don't maybe setups where uninstall succeeds are all using NodePort?
Anyhow I meanwhile think it would be worth a try, to make traefik the thing that always get's deleted as last component.

**Comment by thardeck** [comment]
As discussed in the planning moved back to the icebox because of unsupported setup for now.

**Comment by jimmykarily** [comment]
I can't see how the second issue is relevant to the first one:

```
unable to recognize "": no matches for kind "QuarksSecret"
```

vs finalizers issue.

It could also be some race condition but I don't think we are looking at the same issue.

Regarding the issue in the description, I've seen a similar failure when the cert manager was never able to access the cluster and solve the DNS challenge. How much time did you wait before running `epinio uninstall`? Do you remember if the certs were created successfully before running the uninstall? I don't think it needs DNS to be working in order to delete things. It's just the facts that is was never able to create the certs in the first place.

Even if that is the case, maybe we should be more brutal when uninstalling Epinio but I'm not sure overriding finalizers is a good idea. Maybe we should find out why the finalizers are there in the first place and find a way to avoid this situation, even when DNS never worked (e.g. user chose an installation method and then decided to switch to something else without setting up the DNS).

So regarding this:

> on epinio install: wait until system-domain resolves to the matching public traefik service IP, before we install cert-manager

This can be achieved with the 2 step installation

and regarding this:

> on epinio uninstall: delete cert-manager, before we remove traefik

we need to verify that the removed Traefik was the issue and not the DNS that never worked so it would fail anyway (no matter what the order of uninstall is).
