### ISSUE TITLE
Scaling an app to zero prevents epinio from working

### ISSUE THREAD

**Issue by thardeck** [epinio/epinio#536]
If you scale down an app with `epinio app update --instances 0` to zero, epinio is not able to fix it afterwards because it can not connect anymore.

This can be fixed manually by using k9s to increase the replicas.

It should be possible to scale to zero to basically pause an app, and it is possible when done directly in k9s.

## Acceptance criteria
* Scaling down an app to 0 is possible
* The app can be scaled up again with epinio

**Comment by andreas-kupries** [comment]
This feels to me that it falls under #347 . I.e. the abstraction could hold the fact that the app exists, even if it has no active workload.

**Comment by andreas-kupries** [comment]
Replicated. Confirmed.

Server crashes

```
listening on localhost on port 80
2021/06/29 07:37:46 http: panic serving 127.0.0.1:41354: runtime error: index out of range [0] with length 0
goroutine 371 [running]:
net/http.(*conn).serve.func1(0xc0002fc000)
	/usr/local/go/src/net/http/server.go:1800 +0x139
panic(0x1afd200, 0xc000a93ea0)
	/usr/local/go/src/runtime/panic.go:975 +0x3e3
github.com/epinio/epinio/internal/application.(*Workload).Complete(0xc00023ad18, 0x207ab80, 0xc0007914a0, 0x0, 0x0, 0x0)
	/home/work/SUSE/dev/epinio/internal/application/workload.go:228 +0x93d
github.com/epinio/epinio/internal/application.List(0x207ab80, 0xc0007914a0, 0xc0001f61a0, 0xc0003e6e81, 0x9, 0xc0003e6e01, 0x0, 0x0, 0xc00023b7c0, 0x41751e)
	/home/work/SUSE/dev/epinio/internal/application/application.go:133 +0x2e6
github.com/epinio/epinio/internal/api/v1.ApplicationsController.Index(0x0, 0x2074e80, 0xc000266620, 0xc0000ab100, 0x1a59f60, 0xc000064700)
	/home/work/SUSE/dev/epinio/internal/api/v1/applications.go:95 +0x1a9
github.com/epinio/epinio/internal/api/v1.errorHandler.func1(0x2074e80, 0xc000266620, 0xc0000ab100)
	/home/work/SUSE/dev/epinio/internal/api/v1/router.go:45 +0x43
net/http.HandlerFunc.ServeHTTP(0xc000557130, 0x2074e80, 0xc000266620, 0xc0000ab100)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/julienschmidt/httprouter.(*Router).Handler.func1(0x2074e80, 0xc000266620, 0xc0000ab000, 0xc000354880, 0x1, 0x2)
	/home/work/SUSE/go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:275 +0x1c8
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc0006086c0, 0x2074e80, 0xc000266620, 0xc0000ab000)
	/home/work/SUSE/go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0xc37
github.com/epinio/epinio/internal/cli.logRequestHandler.func1(0x2074e80, 0xc000266620, 0xc0000aad00)
	/home/work/SUSE/dev/epinio/internal/cli/server.go:105 +0x287
net/http.HandlerFunc.ServeHTTP(0xc000565860, 0x2074e80, 0xc000266620, 0xc0000aad00)
	/usr/local/go/src/net/http/server.go:2041 +0x44
net/http.(*ServeMux).ServeHTTP(0x2efa640, 0x2074e80, 0xc000266620, 0xc0000aad00)
	/usr/local/go/src/net/http/server.go:2416 +0x1a5
net/http.serverHandler.ServeHTTP(0xc0001e6000, 0x2074e80, 0xc000266620, 0xc0000aad00)
	/usr/local/go/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc0002fc000, 0x207aac0, 0xc000141a80)
	/usr/local/go/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2962 +0x35c
2021/06/29 07:37:59 http: panic serving 127.0.0.1:41902: runtime error: index out of range [0] with length 0
```

**Comment by andreas-kupries** [comment]
Yep,

https://github.com/epinio/epinio/blob/main/internal/application/workload.go#L222
```
	app.StageID = pods.Items[0].ObjectMeta.Labels["epinio.suse.org/stage-id"]
```

assumes that there is at least one pod around, to pull the stageID from.

**Comment by jimmykarily** [comment]
> Yep,
> 
> https://github.com/epinio/epinio/blob/main/internal/application/workload.go#L222
> 
> ```
> 	app.StageID = pods.Items[0].ObjectMeta.Labels["epinio.suse.org/stage-id"]
> ```
> 
> assumes that there is at least one pod around, to pull the stageID from.

This information exists also on the Deployment. The deployment is there even when there are no pods. Otoh, a deployment may not always exist in the near future (if an app was created without pushing), so maybe it's worth checking that before trying to find the stageID from the deployment.
