### ISSUE TITLE
Crash in command completion for `app show`

### ISSUE THREAD

**Issue by andreas-kupries** [epinio/epinio#557]
Seen on branch `main`, commit 14c682e34b0c3c07fc2c2251d2f3cfd3f49dedb8

The command completion for `app show` is not working
An app `hello` was present, and completion did not pick it up.
Trialing the relevant command directly:

```
ep __complete app show h
```

showed a crash.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1292f6a]

goroutine 1 [running]:
golang.org/x/time/rate.(*Limiter).WaitN(0xc00003aa50, 0x0, 0x0, 0x1, 0x0, 0x0)
	/home/work/SUSE/go/pkg/mod/golang.org/x/time@v0.0.0-20201208040808-7e3f01d25324/rate/rate.go:237 +0xba
golang.org/x/time/rate.(*Limiter).Wait(...)
	/home/work/SUSE/go/pkg/mod/golang.org/x/time@v0.0.0-20201208040808-7e3f01d25324/rate/rate.go:219
k8s.io/client-go/util/flowcontrol.(*tokenBucketRateLimiter).Wait(0xc000736ee0, 0x0, 0x0, 0xc0000f2988, 0x0)
	/home/work/SUSE/go/pkg/mod/k8s.io/client-go@v0.20.5/util/flowcontrol/throttle.go:106 +0x4b
k8s.io/client-go/rest.(*Request).tryThrottle(0xc0008f6000, 0x0, 0x0, 0xabcb2c, 0xc0006bd200)
	/home/work/SUSE/go/pkg/mod/k8s.io/client-go@v0.20.5/rest/request.go:587 +0xa4
k8s.io/client-go/rest.(*Request).request(0xc0008f6000, 0x0, 0x0, 0xc0000f2ee8, 0x0, 0x0)
	/home/work/SUSE/go/pkg/mod/k8s.io/client-go@v0.20.5/rest/request.go:860 +0x29d
k8s.io/client-go/rest.(*Request).Do(0xc0008f6000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/work/SUSE/go/pkg/mod/k8s.io/client-go@v0.20.5/rest/request.go:964 +0xe0
k8s.io/client-go/kubernetes/typed/core/v1.(*nodes).List(0xc00012f0e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/work/SUSE/go/pkg/mod/k8s.io/client-go@v0.20.5/kubernetes/typed/core/v1/node.go:88 +0x19a
github.com/epinio/epinio/helpers/kubernetes/platform/kind.(*kind).Detect(0xc000466360, 0x0, 0x0, 0xc000458000, 0x0)
	/home/work/SUSE/dev/epinio/helpers/kubernetes/platform/kind/kind.go:25 +0xac
github.com/epinio/epinio/helpers/kubernetes.(*Cluster).detectPlatform(0xc000721c80, 0x0, 0x0)
	/home/work/SUSE/dev/epinio/helpers/kubernetes/cluster.go:127 +0x92
github.com/epinio/epinio/helpers/kubernetes.GetCluster(0x0, 0x0, 0x0, 0x6, 0xc000686ac0)
	/home/work/SUSE/dev/epinio/helpers/kubernetes/cluster.go:106 +0x105
github.com/epinio/epinio/internal/cli/clients.NewEpinioClient(0x0, 0x0, 0xc0000e1900, 0x0, 0x0, 0x0)
	/home/work/SUSE/dev/epinio/internal/cli/clients/client.go:68 +0x60
```

**Comment by andreas-kupries** [comment]
Given that the core of command completion is accessible via `__complete` I recommend that we start writing tests for command completion also.

**Comment by andreas-kupries** [comment]
The crash happens in the `GetCluster` on the the `NewEpinioClient()`. That same call works when the command itself (`app show` is run.

**Comment by andreas-kupries** [comment]
There is a difference in the context structure. The command itself gets the background context out of `cmd.Context()`. In the ValidArgsE function used by completion that same `cmd.Context()` returns `nil`.

**Comment by andreas-kupries** [comment]
Using an explicit `context.Background()` and `GetCluster` works. It still crashes somewhere later, in the same manner. Ah, another cmd.Context().

**Comment by andreas-kupries** [comment]
And that is a fix. I suspect that this issue is in all the `ValidArgsE` ... Checking ...
