### ISSUE TITLE
Gitea deployment didn't come up on first attempt (due to multiple default storage classes)

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#583]
I installed longhorn which apparently didn't clear the `is-default-class` flag from the local-path provisioner (I'll report that bug there...) but this cascaded into a poor error when reinstalling epinio. 

The error that got shown left off the part of the error that would have helped diagnose this easier:

`✔️  Tekton deployed
.....................................................................................................................................................................................................................................................panic: Deployment gitea failed with error: failed waiting Gitea postgresql deployment to exist: timed out waiting for the condition

goroutine 54 [running]:
github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Install.func1(0xc0000ef3e0, 0x205f4b0, 0xc000128000, 0x2069d90, 0xc0004759a0, 0x206f998, 0xc00022bc40, 0xc00022bbe4)
        /home/runner/work/epinio/epinio/internal/cli/clients/install_client.go:150 +0x239
created by github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Install
        /home/runner/work/epinio/epinio/internal/cli/clients/install_client.go:147 +0xe59`

**Comment by agracey** [comment]
Hmm, even after correcting the multiple defaults, it appears that either my longhorn install is busted or Epinio doesn't work with longhorn storage. I can try to diagnose my set up later this week.

**Comment by agracey** [comment]
This was 100% a problem with my Longhorn install. Turns out Pop OS doesn't have some of the needed storage drivers installed by default...

I'll close this and open a new ticket more generically about passing better errors through.
