### ISSUE TITLE
Uncatched timeout (panic) when deleting linkerd

### ISSUE THREAD

**Issue by kkaempf** [epinio/epinio#595]
What I did

- minikube 1.21 with k8s 1.20.7
- fresh minikube install (testing #187)
- compiled epinio from src @ 3a07a4d5c083ab33c813781509c7c3e9c6652190
- run "epinio install" until Traefik timeout
- run "epinio uninstall"

This is what happened:

```
⚠️  Skipping Epinio because namespace either doesn't exist or not owned by Epinio
..
✔️  Traefik removed

🚢 Removing Linkerd...............................................................................................................................................................................................................................................................................................................panic: failed to delete namespace: timed out waiting for the condition

goroutine 1 [running]:
github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Uninstall(0xc000893200, 0x2c44ee0, 0x0, 0x0)
	/abuild/projects/rancher/epinio/epinio/internal/cli/clients/install_client.go:215 +0xc57
github.com/epinio/epinio/internal/cli.Uninstall(0x2c44ee0, 0x2c8d758, 0x0, 0x0, 0x0, 0x0)
	/abuild/projects/rancher/epinio/epinio/internal/cli/uninstall.go:26 +0xa7
github.com/spf13/cobra.(*Command).execute(0x2c44ee0, 0x2c8d758, 0x0, 0x0, 0x2c44ee0, 0x2c8d758)
	/abuild/projects/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000b5600, 0xc000193df8, 0x1, 0x1)
	/abuild/projects/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/abuild/projects/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/epinio/epinio/internal/cli.Execute()
	/abuild/projects/rancher/epinio/epinio/internal/cli/root.go:80 +0xb17
main.main()
	/abuild/projects/rancher/epinio/epinio/main.go:6 +0x25
```

**Comment by kkaempf** [comment]
A subsequent `epinio install` reports
```
⚠️  Linkerd already installed, skipping
```

**Comment by kkaempf** [comment]
Maybe this is relevant:

The log of `linkerd/linkerd-uninstall-ntsvp:linkerd-uninstall` shows
> Please uninject the following pods before uninstalling the control-plane:                                                                                                                 
     * traefik-857d48b764-gjlqf                                                                                                                                                             
 No resources found

**Comment by jimmykarily** [comment]
I expect this kind of issues to be gone with the new declarative installer/uninstaller. I'll close this now and we can revisit it if for some reason we stick to the current installer.
