### ISSUE TITLE
`epinio install` panics during gitea install

### ISSUE THREAD

**Issue by kkaempf** [epinio/epinio#615]
#### Environment

- minikube 1.22.0
- k8s 1.21.2
- epinio @ e350a06bcaf70077d17c92c5c82746bb863d5529

#### Error message

````
✔️  Tekton deployed
...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................panic: Deployment gitea failed with error: failed waiting Gitea gitea deployment to come up: Failed waiting for gitea-0: timed out waiting for the condition
Pod Events: 
0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
Successfully assigned gitea/gitea-0 to minikube
Search Line limits were exceeded, some search paths have been omitted, the applied search line is: gitea.svc.cluster.local svc.cluster.local cluster.local nue.suse.com suse.de suse.cz
Container image "gitea/gitea:1.13.0" already present on machine
Created container init
Started container init
Back-off restarting failed container


goroutine 184 [running]:
github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Install.func1(0xc000860d50, 0x2069f50, 0xc0000401a0, 0x2074830, 0xc000843cc0, 0x207a3d8, 0xc00032b960, 0xc00032b924)
	/abuild/projects/rancher/epinio/epinio/internal/cli/clients/install_client.go:147 +0x239
created by github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Install
	/abuild/projects/rancher/epinio/epinio/internal/cli/clients/install_client.go:144 +0xd7a
````

**Comment by agracey** [comment]
Can you look at the PVC to see if there's an event explaining why it isn't bound?

My bet would be that there's no default StorageClass set

**Comment by agracey** [comment]
Is this still an issue with 0.0.24?

**Comment by kkaempf** [comment]
Haven't seen this one with recent versions.
