### ISSUE TITLE
A different installation failure on windows

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#637]
Running into this: 

Using Rancher Desktop with k8s v1.21.1

`PS C:\Users\Andrew Gracey> .\bin\epinio install --no-colors

🚢 Epinio installing...

Configuration...
  🧭  skip-traefik: false
  🧭  skip-linkerd: false
  🧭  system_domain:
  🧭  email_address: epinio@suse.com
  🧭  user: 93c5969043634223
  🧭  password: 8fdfcdb275835d50
  🧭  tls-issuer: epinio-ca
  🧭  use-internal-registry-node-port: true

🚢 Deploying Linkerd...
✔️  Linkerd deployed

⚠️  System Ingress present, skipping
.
✔️  Using system_domain: 172.17.58.242.omg.howdoi.website

🚢 Deploying Kubed...
🚢 Deploying Tekton...
🚢 Deploying CertManager...

🚢 Deploying Gitea...🚢 Deploying Epinio...
🚢 Deploying Registry...
🚢 Deploying ServiceCatalog...panic: Deployment cert-manager failed with error: Failed installing CertManager: Error: unknown flag: --enable-certificate-owner-ref

goroutine 15 [running]:
github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Install.func1(0xc000349f50, 0x203bc30, 0xc00003a040, 0x2046950, 0xc000565400, 0x204c808, 0xc000142b50, 0xc000142b30)
        /home/runner/work/epinio/epinio/internal/cli/clients/install_client.go:147 +0x23f
created by github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Install
        /home/runner/work/epinio/epinio/internal/cli/clients/install_client.go:144 +0xd7a`

**Comment by agracey** [comment]
Sorry, I'm actually on k3s v1.21.1 (via Rancher Desktop)

**Comment by agracey** [comment]
Interestingly enough, pointing my WSL at the same cluster lets the install work. Then doing `update-credential` set everything correctly.

**Comment by agracey** [comment]
Dup of #659
