### ISSUE TITLE
Azure AKS - linkerd fails to uninstall

### ISSUE THREAD

**Issue by svollath** [epinio/epinio#647]
Running epinio 0.0.19 on Azure AKS (kube 1.19.11, 2 Standard_D3_v2 nodes).

I ran `epinio install-ingress` (which installed successfully) and then `epinio uninstall`.

`epinio uninstall` output:
```
> ./epinio-0.0.19 uninstall

🚢 Epinio uninstalling...

🚢 Removing Epinio...
🚢 Removing Registry...



🚢 Removing Traefik...
🚢 Removing ServiceCatalog...🚢 Removing Gitea...🚢 Removing CertManager...
🚢 Removing Kubed...
🚢 Removing Minibroker...🚢 Removing GoogleServices...
🚢 Removing Tekton...
⚠️  Skipping Epinio because namespace either doesn't exist or not owned by Epinio

⚠️  Skipping Kubed because namespace either doesn't exist or not owned by Epinio

⚠️  Skipping Registry because namespace either doesn't exist or not owned by Epinio

⚠️  Skipping Gitea because namespace either doesn't exist or not owned by Epinio

⚠️  Skipping CertManager because namespace either doesn't exist or not owned by Epinio

⚠️  Skipping ServiceCatalog because namespace either doesn't exist or not owned by Epinio

⚠️  Skipping Minibroker because namespace either doesn't exist or not owned by Epinio

⚠️  Skipping GoogleServices because namespace either doesn't exist or not owned by Epinio

⚠️  Skipping Tekton staging because namespace either doesn't exist or not owned by Epinio
......
✔️  Traefik removed

🚢 Removing Linkerd................................................................................................................................................................................................................................................................................................................panic: failed to delete namespace: timed out waiting for the condition

goroutine 1 [running]:
github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Uninstall(0xc000641920, 0x2070e30, 0xc000196000, 0x0, 0x0)
        /home/runner/work/epinio/epinio/internal/cli/clients/install_client.go:209 +0xb97
github.com/epinio/epinio/internal/cli.Uninstall(0x2c5bfa0, 0x2ca48b8, 0x0, 0x0, 0x0, 0x0)
        /home/runner/work/epinio/epinio/internal/cli/uninstall.go:26 +0x93
github.com/spf13/cobra.(*Command).execute(0x2c5bfa0, 0x2ca48b8, 0x0, 0x0, 0x2c5bfa0, 0x2ca48b8)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x2c59840, 0x0, 0x1c784a9, 0xe)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/epinio/epinio/internal/cli.Execute()
        /home/runner/work/epinio/epinio/internal/cli/root.go:43 +0x55
main.main()
        /home/runner/work/epinio/epinio/main.go:6 +0x25
```

Pods remaining:
```
> kubectl get pods -A
NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE
kube-system   azure-ip-masq-agent-wgt2z                 1/1     Running     0          13m
kube-system   azure-ip-masq-agent-xhkkp                 1/1     Running     0          13m
kube-system   coredns-76c97c8599-2f7wz                  1/1     Running     0          13m
kube-system   coredns-76c97c8599-4swpv                  1/1     Running     0          14m
kube-system   coredns-autoscaler-599949fd86-z59hp       1/1     Running     0          14m
kube-system   kube-proxy-68twp                          1/1     Running     0          13m
kube-system   kube-proxy-lf657                          1/1     Running     0          13m
kube-system   metrics-server-77c8679d7d-trltk           1/1     Running     0          14m
kube-system   tunnelfront-84d476897d-bkms8              1/1     Running     0          14m
linkerd       linkerd-controller-6cc4496649-l6522       2/2     Running     0          6m52s
linkerd       linkerd-destination-b94cb7d69-k58h7       2/2     Running     0          6m52s
linkerd       linkerd-identity-7ddbd568db-qcrlt         2/2     Running     0          6m52s
linkerd       linkerd-install-xgm7r                     0/1     Completed   0          7m4s
linkerd       linkerd-proxy-injector-7b6d9bf76b-9tl2c   2/2     Running     0          6m52s
linkerd       linkerd-sp-validator-7dc7dc4998-dcthg     2/2     Running     0          6m52s
linkerd       linkerd-uninstall-r78xr                   0/1     Completed   0          2m53s
```

Linkerd uninstall logs:
```
> kubectl logs linkerd-uninstall-r78xr -n linkerd 
Please uninject the following pods before uninstalling the control-plane:
        * traefik-857d48b764-96hdh
No resources found
```

**Comment by manno** [comment]
Code starts of all the uninstalls and waits for the commands to be issued. Only then it starts the linkerd uninstall. However, issuing a command to the cluster is not the same as waiting for it to finish, so we still end up with races.
